/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cdef6b05-5ad0-4a6c-8fe6-cf88f50d424f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hzNYs76xm",
    "aws_user_pools_web_client_id": "7pr8rc33qi6euj3v99vjs584vc",
    "oauth": {}
};


export default awsmobile;
